Use the deconstructed condition for filter rel
Summary:
In our service, we use `ROW` type to contain two values for our paging
design. This is not really supported by Calcite and causing
compilation errors when generating the query:

```
java.lang.RuntimeException: while resolving method 'gt[class [Ljava.lang.Object;, class
[Ljava.lang.Object;]' in class class org.apache.calcite.runtime.SqlFunctions
```

This is because the in memory filters include the original `ROW` type
instead of the expanded disjunction created by:
`RowValueExpressionConverter`